PINECONE_API_KEY = "pcsk_22reMi_CoW2s5jpVBSzePsuNTNPNbLgVzEb6ZzUynpCpGkECDH2D22NAz4eFdJd94RPmgj"
INDEX_HOST = "https://regulations3-bf89341.svc.aped-4627-b74a.pinecone.io"
INDEX_NAME = "regulations3"
OPENAI_API_KEY = "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"

